<a href="https://colab.research.google.com/github/adx17/machine-learning/blob/main/MIN_MAX_SCALING_____STANDARDIZING____NORMALIZING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**MIN-MAX SCALING , STANDARDIZING ,NORMALIZING**

 ##**IMPORTING MODULES**

In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler,Normalizer

##**DATASETS**

In [13]:
np.random.seed(5)
X=np.random.randn(10,5)

##**MIN-MAX SCALING**

In [15]:
mms=MinMaxScaler()
x_mms=mms.fit_transform(X)

##**STANDARDIZING**

In [16]:
sd=StandardScaler()
x_sd=sd.fit_transform(X)

##**NORMALIZING**

In [17]:
nm=Normalizer()
x_nm=nm.fit_transform(X)

##**PRINTING RESULTS**

In [21]:
print("MIN-MAX SCALED RESULT :\n",x_mms)
print("STANDARDIZED RESULT :\n",x_sd)
print("NORMALIZED RESULT :\n",x_nm)

MIN-MAX SCALED RESULT :
 [[0.58877385 0.28067344 1.         0.59541141 0.5499758 ]
 [1.         0.         0.08485383 0.80333949 0.41375878]
 [0.         0.34181689 0.155345   1.         0.        ]
 [0.1774926  1.         0.8263697  0.         0.71587302]
 [0.07644611 0.02541913 0.         0.51482327 0.82484926]
 [0.68649268 0.46994353 0.15398793 0.71617883 0.48316896]
 [0.7155467  0.13474601 0.26211805 0.66682958 0.49978922]
 [0.51958724 0.53716389 0.66816875 0.67354086 1.        ]
 [0.31957948 0.20940313 0.29449601 0.88270731 0.59956869]
 [0.89531819 0.99415321 0.41370397 0.5555731  0.48481669]]
STANDARDIZED RESULT :
 [[ 0.27882079 -0.34819205  1.92116629 -0.17720661 -0.02848183]
 [ 1.54088133 -1.17180158 -0.94182078  0.63386672 -0.56701289]
 [-1.52813683 -0.16877239 -0.72129281  1.40098819 -2.20279938]
 [-0.98340882  1.76260339  1.37797295 -2.49975157  0.6273893 ]
 [-1.29352234 -1.09721156 -1.20728156 -0.49155996  1.05822454]
 [ 0.57872167  0.20720306 -0.72553834  0.29387568 -0.292